nombre = input("Ingrese su nombre: ")
apellido = input("Ingrese su apellido: ")
codigo_seccion = input("Ingrese su Código-Sección: ")
sede = input("Ingrese su sede: ")
print("Nombre: " + nombre + " " + apellido)
print("Código-Sección: " + codigo_seccion)
print("Sede: " + sede)